### ISSUE TITLE
Request for Alpha Release 2.0a1

### ISSUE THREAD

**Issue by jensens** [collective/plone.recipe.varnish#16]
As you may have noticed I overhauled the recipe to work with varnish 4. Now we're using it in a project and it works. I would like to release an 2.0a1. Can one with permissions do a release or add me to the list of owners at pypi so I can do myself? TIA!

**Comment by cleberjsantos** [comment]
@jensens I've a doubt as the line 151 in https://github.com/collective/plone.recipe.varnish/blob/master/plone/recipe/varnish/templates/varnish4.vcl.jinja2#L151.

Could we add this snippet code `set req.http.Cookie = regsuball(req.http.Cookie, ";(statusmessages|__ac|_ZopeId)=", "; \1=");` below the line 151? This line's necessary for Zope/Plone authentication.

**Comment by jensens** [comment]
i think this is what the expression ``{% for name in cookiewhitelist %}{{name}}{% if not loop.last %}|{% endif %}{% endfor %}`` builds from the configureable cookiewhitelist, defaults defined here
https://github.com/collective/plone.recipe.varnish/blob/master/plone/recipe/varnish/recipe.py#L27

**Comment by cleberjsantos** [comment]
Oh, okay :+1: cool!

**Comment by mauritsvanrees** [comment]
@jensens I have given you PyPI rights.

I must confess I have not looked at the recent changes. But a release seems a good idea.

**Comment by jensens** [comment]
2.0a1 released. There is still some work left, but this release finally works. Test need some love too (testing buildout is always a pita )

**Comment by jean** [comment]
Hi Jens & all

I've added a pull request and a few issues ..

--
jean                                              . .. .... //\\\oo///\\

**Comment by yurj** [comment]
> i think this is what the expression `{% for name in cookiewhitelist %}{{name}}{% if not loop.last %}|{% endif %}{% endfor %}` builds from the configureable cookiewhitelist, defaults defined here https://github.com/collective/plone.recipe.varnish/blob/master/plone/recipe/varnish/recipe.py#L27

Hi!

 I've found `statusmessages` must be added to cookies that create a MISS. So `statusmessages` should be added here:

https://github.com/collective/plone.recipe.varnish/blob/702768b5dfe4cf6995b00110ee63f8940205b94d/plone/recipe/varnish/recipe.py#L29

"statusmessages|auth_token|__ac(|_(name|password|persistent))=":"\.(js|css|kss)$"

Otherwise, when you logout, the "Info: You are now logged out." will not appear until you hit a page not in the cache. After that, the cookie is removed so it should not be a problem. 

@fredvd what do you think?
