### ISSUE TITLE
Process `grace-*` options

### ISSUE THREAD

**Issue by jean** [collective/plone.recipe.varnish#20]
In `README.txt`, we have `grace-healty` _(sic)_ and `grace-sick`. 
Running buildout reports: _Unused options for varnish-script: 'grace-healthy'._ (or `...healty`). 
Looking at `plone/recipe/varnish/tests/vclgen.rst` I see `gracehealthy` and `gracesick`.

So: should the README be changed to match the test?

**Comment by jean** [comment]
Spelling in README stays, as it follows buildout conventions; spelling in template is due to jinja identifier syntax. 

I've added code to pick up the options in  972ad81 on #17

**Comment by frisi** [comment]
just stumbled over this. the options are used in `plone.recipe.varnish:configuration` rather than `plone.recipe.varnish:script`

https://github.com/collective/plone.recipe.varnish/blob/6.0.0b1/plone/recipe/varnish/recipe.py#L241-L255

so i guess a simple update of the readme will fix that, right?
just move https://github.com/collective/plone.recipe.varnish/blame/6.0.0b1/README.rst#L376-L398 into section *VCL Configuration Generator* (https://github.com/collective/plone.recipe.varnish/blame/6.0.0b1/README.rst#L222)
