### ISSUE TITLE
max header

### ISSUE THREAD

**Issue by loechel** [collective/plone.recipe.varnish#26]
Hi 

I have run into problems on Plone Setup where Plone seams to return to many headers:

Resolution:
set start parameter of varnishd 
`-p http_req_hdr_len=20000` deault is 2k

`-p http_resp_hdr_len=20000` default is 2k

`-p http_max_hdr=256` Default is 64

**Comment by fredvd** [comment]
@loechel: interesting, didn't know about these. Since varnish 3.0 the first two headers (http-req_hdr_len & resp) seem to be 8k according to the Varnish documentation (checked 3 and 4). That's why I probably never experienced this. 

The http_max_hdr is still default 64, so increasing this could help with the number of headers

**Comment by loechel** [comment]
@fredvd well that could also be the ubuntu and debian defaults. I did have problems with Shibboleth, as I get a lots of header lines which are quite big.

Better to have it communicated.
