### ISSUE TITLE
Plone 5.1.2.1 incompatible with plone.recipe.varnish 2.2.0 

### ISSUE THREAD

**Issue by rogeriocdluiz** [collective/plone.recipe.varnish#63]
When i try run buidout to build Varnish in Plone 5.1.2.1 i get the following error:

...
The requirement ('jinja2>=2.7.3') is not allowed by your [versions] constraint (2.5.5).
While:
  Installing.
  Getting section varnish-build.
  Initializing section varnish-build.
  Installing recipe plone.recipe.varnish.
Error: The requirement ('jinja2>=2.7.3') is not allowed by your [versions] constraint (2.5.5)

**Comment by mauritsvanrees** [comment]
In http://dist.plone.org/release/5.1.2/versions.cfg I see `jinja2 = 2.10`. Maybe you have an older pin in your own versions section?
Note that an own pin could be for `Jinja2` with a capital `J`.

And strangely, in the http://dist.plone.org/release/5.1.2/ folder, we have a `Jinja2-2.5.5.tar.gz` file, so there is a mismatch between the version that is really pinned by Plone and the file that is there. But that shouldn't be the problem here.

**Comment by jensens** [comment]
Since Plone 5.1 is no longer supported I close the issue.
