### ISSUE TITLE
Simplify: support one varnish version

### ISSUE THREAD

**Issue by mauritsvanrees** [collective/plone.recipe.varnish#70]
The master branch of the recipe currently supports varnish 4, with initial support (probably working just fine) for varnish 5 and 6 added in the first quarter of 2018.

There are not a lot of people working on this recipe. It seems good to make it simpler.

We could simplify it to support just one varnish version in a recipe branch. Some big version increases would be in order then:
- recipe branch 4.x supports varnish 4.x (so both 4.0 and 4.1)
- recipe branch 5.x supports varnish 5.x.
- recipe branch master supports varnish 6.x

Tests would be faster because we only need to test one varnish major version.
The code would be simpler because we can remove several templates and conditions.
It would be easier to add new options for varnish 6 without fear of introducing bugs for varnish 4.

Perhaps also only support one `vcl-version`, though I don't really see which varnish version supports or requires which vcl version.

What do you think?
cc @jensens @fredvd @cleberjsantos

**Comment by fredvd** [comment]
The vcl_version parameter is rather vague, I remember reading the change somewhere, but even varnish 6/master is still using version 4.0 in their builtin.vcl.

I've chatted about plone.recipe.varnish versions with @jensens at the PloneTagung and Maurits about the effort it takes to keep the recipe synced with multiple versions. Varnish didn't make it easier when they switced to bi-yearly major versions, but the current Version overview is in another way confusing: http://varnish-cache.org/releases/index.html. 

At the moment, Varnish 6.0.X/6.0.3 is the supported LTS version, and the 6.2 version is the freshed and supported version.   Varnish 4 got one more release with 4.1.11, but is also ofificially end of Life since March 15 according to this mailinglist message from Varnish: https://varnish-cache.org/lists/pipermail/varnish-announce/2019-February/000733.html , but at the same time Varnish Software wil continue support their commercial version of Varnish 4. 

So only 6.0.3 and 6.2 are 'current' Varnish versions.

End of last year I tested varnish 6.1.1 with the latest plone.recipe.varnish release by using master as an interim release and setting varnish_version and vcl_version accordingly. It just worked with the config generated. 

```[versions]
varnish-url = ${versions:base-url}varnish-6.1.1.tgz
plone.recipe.varnish = 2.2.1.dev0+zest0

[varnish-configuration]
varnish_version = 6
vcl-version = 4.1
vcl_hash =   
       hash_data(req.url);
       return(lookup);

[varnish-build]
extra_options = --with-sphinx-build=false```

Varnish tweaks and improves the software all the time, but unless you really want to experiment with new features or do niche kind of things, the needed vcl in front of Plone is rather stable.

The big question: who are 'we' maintaining this recipe for? The largest group of users is probably trusting the recipe as a black box and doesn't know the inner workings and hopes/expects it works good enough together with their Plone version. A smaller group might use the recipe ootb first but then copy and modify the generated vcl into a custom version for their project. 

And then there's the small group of developers/contributors to the recipe, mainly @jensens and @cleberjsantos doing the most work and some others like me and @mauritsvanrees patching and fixing small issues for our own setups. The main conflict here is that we have some more inside Varnish knowledge and more specific use cases or optimisations we'd like to standardise in the recipe, but these are not necessarily useful to the black box recipe user. Then we parametrise these improvements, but to use the correctly you very soon have to know more of the inner workings, which defeats the purpose for our black box users. :-)

And because 'we' don't want to stand on or fellow maintainers toes, many of the improvements are an extra switch/parameter to not interfere with improvements from other maintainers :-P

collective.recipe.solrinstance has had the same curse: the people knowledgeable enough to build the perfect 'black box' solr config for Plone have no purpose for maintaining the recipe once they master the configuration and want to configure advanced stuff. Folding the advanced template generation parameters and desiging templlates/switches back into the recipe (and supporting 4 solr major versions) only makes the recipe more complex and adds an extra abstraction layers the 'ootb' users can't use. 

If we can release the current p.r.varnish master as some final 2.1.x versions to keep installed base stable, I'd suggest we create an lts-6 branch where clean up the recipe for 6.0.X only, from which we create pypi releases like  plone.recipe.varnish-6.0.x.p. So when varnish releases 6.0.3 LTS, we can release a plone.recipe.varnish-6.0.3.1  (and update the last minor to .2 .3 for our own patch releases.

Users can still override the url in the :build section of the recipe, but the release numbering at least shows which varnish version is supported ootb and where the maintainers of the recipe try have conservative but correct caching. Which is already a pain, because there isn't a default Plone stack setup, do you use v

And master of plone.recipe.varnish repo would try to support only 'fresh' release of varnish ootb as much as possible, and could be released on pypi like 6.2.0.1 for the recently announced http://varnish-cache.org/releases/rel6.2.0.html#rel6-2-0
